<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TemaMinuta extends \App\Entity\TemaMinuta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromisoInicio', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromisoFin', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'requerimiento', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'lineaGuia', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromisoAccion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromiso', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'observacion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'ultimoTemaIngresado', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'ultimoModificacion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'parent', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'ultimoRoot', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'bloque', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'idReunion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'idCategoria', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'idEstatus'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromisoInicio', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromisoFin', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'requerimiento', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'lineaGuia', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromisoAccion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'compromiso', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'observacion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'ultimoTemaIngresado', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'ultimoModificacion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'parent', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'ultimoRoot', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'bloque', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'idReunion', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'idCategoria', '' . "\0" . 'App\\Entity\\TemaMinuta' . "\0" . 'idEstatus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TemaMinuta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompromisoInicio(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompromisoInicio', []);

        return parent::getCompromisoInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompromisoInicio(?\DateTimeInterface $compromisoInicio): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompromisoInicio', [$compromisoInicio]);

        return parent::setCompromisoInicio($compromisoInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompromisoFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompromisoFin', []);

        return parent::getCompromisoFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompromisoFin(?\DateTimeInterface $compromisoFin): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompromisoFin', [$compromisoFin]);

        return parent::setCompromisoFin($compromisoFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequerimiento(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequerimiento', []);

        return parent::getRequerimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequerimiento(?string $requerimiento): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequerimiento', [$requerimiento]);

        return parent::setRequerimiento($requerimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineaGuia(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineaGuia', []);

        return parent::getLineaGuia();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineaGuia(?string $lineaGuia): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineaGuia', [$lineaGuia]);

        return parent::setLineaGuia($lineaGuia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompromisoAccion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompromisoAccion', []);

        return parent::getCompromisoAccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompromisoAccion(?string $compromisoAccion): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompromisoAccion', [$compromisoAccion]);

        return parent::setCompromisoAccion($compromisoAccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompromiso(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompromiso', []);

        return parent::getCompromiso();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompromiso(?string $compromiso): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompromiso', [$compromiso]);

        return parent::setCompromiso($compromiso);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion(?string $observacion): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', [$observacion]);

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function isUltimoTemaIngresado(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUltimoTemaIngresado', []);

        return parent::isUltimoTemaIngresado();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoTemaIngresado(bool $ultimoTemaIngresado): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoTemaIngresado', [$ultimoTemaIngresado]);

        return parent::setUltimoTemaIngresado($ultimoTemaIngresado);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimoModificacion(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimoModificacion', []);

        return parent::getUltimoModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoModificacion(?\DateTimeInterface $ultimoModificacion): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoModificacion', [$ultimoModificacion]);

        return parent::setUltimoModificacion($ultimoModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(?int $parent): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function isUltimoRoot(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUltimoRoot', []);

        return parent::isUltimoRoot();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoRoot(bool $ultimoRoot): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoRoot', [$ultimoRoot]);

        return parent::setUltimoRoot($ultimoRoot);
    }

    /**
     * {@inheritDoc}
     */
    public function getBloque(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBloque', []);

        return parent::getBloque();
    }

    /**
     * {@inheritDoc}
     */
    public function setBloque(int $bloque): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBloque', [$bloque]);

        return parent::setBloque($bloque);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdReunion(): ?\App\Entity\Minuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdReunion', []);

        return parent::getIdReunion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdReunion(?\App\Entity\Minuta $idReunion): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdReunion', [$idReunion]);

        return parent::setIdReunion($idReunion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategoria(): ?\App\Entity\Categoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategoria', []);

        return parent::getIdCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategoria(?\App\Entity\Categoria $idCategoria): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategoria', [$idCategoria]);

        return parent::setIdCategoria($idCategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstatus(): ?\App\Entity\EstatusMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstatus', []);

        return parent::getIdEstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstatus(?\App\Entity\EstatusMinuta $idEstatus): \App\Entity\TemaMinuta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstatus', [$idEstatus]);

        return parent::setIdEstatus($idEstatus);
    }

}
