<?php

namespace Container7xrMFSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEstatusMinutaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EstatusMinutaRepository' shared autowired service.
     *
     * @return \App\Repository\EstatusMinutaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EstatusMinutaRepository'] = new \App\Repository\EstatusMinutaRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
