<?php

namespace Container7xrMFSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LogRepository' shared autowired service.
     *
     * @return \App\Repository\LogRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LogRepository'] = new \App\Repository\LogRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
