<?php

namespace Container7xrMFSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeccionMinutaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SeccionMinutaRepository' shared autowired service.
     *
     * @return \App\Repository\SeccionMinutaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SeccionMinutaRepository'] = new \App\Repository\SeccionMinutaRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
