<?php

namespace Container7xrMFSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemaUsuarioRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TemaUsuarioRepository' shared autowired service.
     *
     * @return \App\Repository\TemaUsuarioRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TemaUsuarioRepository'] = new \App\Repository\TemaUsuarioRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
