<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7xrMFSb\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7xrMFSb/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container7xrMFSb.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container7xrMFSb\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container7xrMFSb\App_KernelProdContainer([
    'container.build_hash' => '7xrMFSb',
    'container.build_id' => '9fa8c0db',
    'container.build_time' => 1663259176,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7xrMFSb');
