<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'principal' => [[], ['_controller' => 'App\\Controller\\HomeController::login'], [], [['text', '/']], [], [], []],
    'login' => [['alerta'], ['alerta' => null, '_controller' => 'App\\Controller\\HomeController::login'], [], [['variable', '/', '[^/]++', 'alerta', true], ['text', '/login']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/inicio']], [], [], []],
    'minuta' => [[], ['_controller' => 'App\\Controller\\MinutaController::index'], [], [['text', '/minuta']], [], [], []],
    'usuario' => [['id_user'], ['id_user' => null, '_controller' => 'App\\Controller\\UsuarioController::index'], [], [['variable', '/', '[^/]++', 'id_user', true], ['text', '/usuario']], [], [], []],
    'tema' => [['busqueda', 'id_registro'], ['busqueda' => null, 'id_registro' => null, '_controller' => 'App\\Controller\\MinutaController::tema'], [], [['variable', '/', '[^/]++', 'id_registro', true], ['variable', '/', '[^/]++', 'busqueda', true], ['text', '/tema']], [], [], []],
    'nuevo' => [['tabla'], ['tabla' => null, '_controller' => 'App\\Controller\\MinutaController:nuevo'], [], [['variable', '/', '[^/]++', 'tabla', true], ['text', '/nuevo']], [], [], []],
    'ver' => [['tabla', 'id_minuta', 'id_registro'], ['tabla' => null, 'id_minuta' => null, 'id_registro' => null, '_controller' => 'App\\Controller\\MinutaController:ver'], [], [['variable', '/', '[^/]++', 'id_registro', true], ['variable', '/', '[^/]++', 'id_minuta', true], ['variable', '/', '[^/]++', 'tabla', true], ['text', '/ver']], [], [], []],
    'actualizar' => [['tabla', 'id_minuta', 'id_registro'], ['tabla' => null, 'id_minuta' => null, 'id_registro' => null, '_controller' => 'App\\Controller\\MinutaController:actualizar'], [], [['variable', '/', '[^/]++', 'id_registro', true], ['variable', '/', '[^/]++', 'id_minuta', true], ['variable', '/', '[^/]++', 'tabla', true], ['text', '/actualizar']], [], [], []],
    'borrar' => [['tabla', 'id_minuta', 'id_registro'], ['tabla' => null, 'id_minuta' => null, 'id_registro' => null, '_controller' => 'App\\Controller\\MinutaController:borrar'], [], [['variable', '/', '[^/]++', 'id_registro', true], ['variable', '/', '[^/]++', 'id_minuta', true], ['variable', '/', '[^/]++', 'tabla', true], ['text', '/borrar']], [], [], []],
    'configuraciones' => [[], ['_controller' => 'App\\Controller\\MinutaController::configuraciones'], [], [['text', '/configuraciones']], [], [], []],
    'buscar_minuta' => [['id_minuta'], ['_controller' => 'App\\Controller\\MinutaController::buscarMinuta'], [], [['variable', '/', '[^/]++', 'id_minuta', true], ['text', '/minuta']], [], [], []],
    'update_minuta' => [['id_minuta', 'tema'], ['id_minuta' => null, 'tema' => null, '_controller' => 'App\\Controller\\MinutaController::update'], [], [['variable', '/', '[^/]++', 'tema', true], ['variable', '/', '[^/]++', 'id_minuta', true], ['text', '/minuta-update']], [], [], []],
    'audiencia_minuta' => [[], ['_controller' => 'App\\Controller\\MinutaController::configuraciones'], [], [['text', '/audiencia']], [], [], []],
    'log_minuta' => [[], ['_controller' => 'App\\Controller\\MinutaController::huella'], [], [['text', '/huella-digital']], [], [], []],
    'updatepos' => [[], ['_controller' => 'App\\Controller\\MinutaController::updatepos'], [], [['text', '/updatepos']], [], [], []],
    'resetpassword' => [[], ['_controller' => 'App\\Controller\\HomeController::resetpassword'], [], [['text', '/resetpassword']], [], [], []],
];
