<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDdh6Adv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDdh6Adv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDdh6Adv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDdh6Adv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDdh6Adv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ddh6Adv',
    'container.build_id' => 'ac88515a',
    'container.build_time' => 1643347202,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDdh6Adv');
