index:
    path: /inicio
    controller: App\Controller\HomeController::index

usuario:
    path: /usuario
    controller: App\Controller\UsuarioController::index

usuario_detalle:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::usuario

guardar_usuario:
    path: /guardar
    controller: App\Controller\UsuarioController::guardar

minuta:
    path: /minuta
    controller: App\Controller\MinutaController::index

seccion_minuta:
    path: /seccion-minuta
    controller: App\Controller\MinutaController::seccionMinuta

registro_minuta:
    path: /registro-minuta
    controller: App\Controller\MinutaController::registroMinuta

audiencia_minuta:
    path: /audiencia
    controller: App\Controller\MinutaController::audienciaMinuta

categoria_minuta:
    path: /categoria
    controller: App\Controller\MinutaController::categoriaMinuta

estaus_minuta:
    path: /estatus
    controller: App\Controller\MinutaController::estatusMinuta

Tema_minuta:
    path: /tema
    controller: App\Controller\MinutaController::temaMinuta

tema_usuario:
    path: /tema-usuario
    controller: App\Controller\MinutaController:temaUsuario

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir